### PR TITLE
Add ability to specify php-fpm environment variables

### PR DESCRIPTION
**Pull request by ndench**
This solves #9 allowing users to specify environment variables that need to be in the php-fpm configuration format of `env[NAME] = VALUE`.

This does not break the default behaviour of only adding variables to the system environment (`/etc/environment` by default), which means this is a backwards compatible change (there is a test to prove this).

Also it opens the way to support other formats of environment variables such as `export NAME=VALUE` for bash and `set NAME VALUE` for fish shell, however this PR is only for the php-fpm format.

I understand that this has added a bit of complexity to what was a very simple role, and that adding more environment formats will make it increasingly complex. If you have any feedback for how I can make this more simple.

### CODE REVIEW

**Comment by franklinkim** [comment]
Sorry, just worked my way down to this one. 

Please see my comment on #9. This role is not intended to manage other configurations besides the `/etc/environment` file and in my opinion, configuring sth like php should be part of a php role.

You might want to take your changes and add your own role to the index and give it a better name like 'yourname.configurations' or sth like that. 

If you do so, I would recommend keeping it as open as possible meaning to define multiple paths, their formats and their content

```YAML
configurations:
  - path: /etc/environment
    format: environment
    config: 
      ...
  - path: /etc/php/7.1/fpm/pool.d/www.conf
    format: php.ini
    config:
       ...
```

**Comment by ndench** [comment]
Ok no worries. I did consider the point you raised in #9 about having separate roles to configure each environment, and also the idea of specifying multiple files with different config. The main reason I went with this approach was because I want the same environment in both PHP and the system. The reason being I want my PHP app to behave the same as any PHP command I run on the cli.

No worries though, I appreciate you wanting to keep your role clean. I've added my role to the galaxy, thanks for the feedback.

**Comment by franklinkim** [comment]
If you want you can add a link to your role here just in case someone stumbles upon this 👍

**Comment by ndench** [comment]
Good idea, here it is: https://github.com/ndench/ansible-role-environment

**Pull request closed without merging**
